language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0-p647
  - 2.1
  - 2.2.3
  - 2.2.3-clang
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
cache: bundler
