language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.2.4-clang
  - 2.3.0
  - 2.3.0-clang
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
cache: bundler
