language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0-p647
  - 2.0.0-p647-clang
  - 2.1.7
  - 2.1.7-clang
  - 2.2.3
  - 2.2.3-clang
  - ruby-head
  - ruby-head-clang
before_install:
  - gem install bundler
cache: bundler
